name: "Close finished milestones"
on:
  schedule:
  - cron: "*/20 * * * *"

jobs:
  milestone-closer:
    runs-on: ubuntu-latest
    steps:
    - uses: instantish/milestone-closer@v1.1.0
      with:
        repo-token: ${{ secrets.MY_TOKEN }}
