# This is a basic workflow to help you get started with Actions

name: PHPUnit test.

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    services:
      mysql:
        image: mysql:5.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: system2_test
        #options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.5'
          extensions: xdebug
          coverage: xdebug
          tools: phpunit:4.8.36
      #- name: Setup Database
      #  # MySQL の起動とデータベースの作成
      #  run: |
      #    sudo systemctl start mysql.service
      #    mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS system2_test;'
      # Runs a set of commands using the runners shell
      - name: version-test
        run: |
          ls -la
          php -v
          phpunit --version
          mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "select version();"
